### ISSUE TITLE
Parsing issue: invalid source attributes in APNIC

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd4#110]
The dumps for APNIC produce the following issues - I think they are not new, but rather we've not imported APNIC mntners before. NTT currently does import them, so we're following that practice:

```
Invalid source APNIC-HM for object MAINT-HK-EGL, expected APNIC
Invalid source APN for object MAINT-EXITRANET1-MY, expected APNIC
Invalid source APNIC-HM for object MAINT-IN-TIMELESS, expected APNIC
Invalid source APNIC-HM for object MAINT-TIMELESS-IN, expected APNIC
Invalid source APNICI for object MAINT-AU-IASSET, expected APNIC
```

As with other incorrect objects, we are currently rejecting these when importing, with errors being logged for them.

**Comment by troy2914** [comment]
if the mntner's not being imported does not cause a problem importing the other objects that point to these mntner.  Why is this ticket still open?
