### ISSUE TITLE
Keep IPv6 support for `!i` queries?

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd4#134]
The IRRDv2/3 manual says:

> Route-set expansions are currently only supported for IPv4 prefixes.

As part of #19, I found that we accidentally added IPv6 support here. Should we retain that, or limit it to the legacy IPv4 prefix behaviour?
In the v2/v4 comparisons, this came up only in two queries, so the impact seems small. I recommend retaining IPv6 support.

**Comment by troy2914** [comment]
To avoid having to parse #19 here are the 2 queries:
!iRS-KROOT-V6,1and !iAS12654:RS-RIS,1 return IPv6 prefixes in IRRDv4 

imo there really should be a new command to return ipv6 prefixes in route-sets in non-ripe mode.
Both of those objects are in the RIPE db.   So presumably there is a RIPE way to query them.

I would restrict '!i' route-set queries from returning IPv6 records.  Clients written to the docs are only expecting IPv4 records to be returned.

**Comment by job** [comment]
I think we may have to retain the `!i` support for ipv6 expansion of route sets for a degree of backwards compatibility:

```
hanna:bgpq3 job$ bgpq3 -h rr.ntt.net -6 RS-KROOT-V6              # a v2 irrd
no ipv6 prefix-list NN
! generated prefix-list NN is empty
ipv6 prefix-list NN deny ::/0

hanna:bgpq3 job$ bgpq3 -h whois.radb.net -6 RS-KROOT-V6    # a v3 irrd
no ipv6 prefix-list NN
ipv6 prefix-list NN permit 2001:7fd::/32
ipv6 prefix-list NN permit 2001:7fd::/48
hanna:bgpq3 job$
```

let's check if the NTT toolset suffers or not before making a decision on what to do next. 

options could be:

- add a configuration option "v2_mode_exclamation_mark_i"
- upgrade ntt toolset (if needed)
- deprecate v6 use of the `!i`

**Comment by job** [comment]
I dont think we can pick one over the other, closing this one in favor of #137
