### ISSUE TITLE
irrd_database_upgrade head is not valid

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#163]
Per the admin/deployment.html I ran `irrd_database_upgrade head` and got the following

/home/irrd/irrd-venv/bin/irrd_database_upgrade head
usage: irrd_database_upgrade [-h] [--config CONFIG_FILE_PATH]
                             [--version VERSION]
irrd_database_upgrade: error: unrecognized arguments: head

encountered in irrd-4.0.0rc1

**Comment by mxsasha** [comment]
I take it from other reports that you found how to do this - I'll correct the documentation.
