### ISSUE TITLE
Add bytes sent to query log message

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#167]
In irrd-4.0.0rc1

irrd is wasting time  (and space) logging thousands of "received query" INFO messages.

**Comment by mxsasha** [comment]
We can lower this to DEBUG easily. However, my understanding was that currently NTT logs all queries in production? That would make it fit INFO level, as that's the recommended level for production.

**Comment by troy2914** [comment]
Hmm, good point.
from the legacy irrd
Jan 17 00:24:40 [18446744073508222720] IRRD Command: !gas30259
Jan 17 00:24:40 [18446744073508222720] IRRD About to lock  --lock_all_mutex_lock--
Jan 17 00:24:40 [18446744073508222720] IRRD Locked --lock_all_mutex_lock--
Jan 17 00:24:40 [18446744073508222720] IRRD Unlocked --lock_all_mutex_lock--
Jan 17 00:24:40 [18446744073508222720] IRRD Done with lock_all
Jan 17 00:24:40 [18446744073508222720] IRRD Sent 609 bytes

The bytes sent is kind of interesting too.

**Comment by mxsasha** [comment]
We could also log the length of the response, at either INFO or DEBUG. Not sure what it would be useful for, but it's fairly easy to add.

**Comment by troy2914** [comment]
Leaving the received query, and adding the response length at INFO would be the consistent with irrd2.

**Comment by mxsasha** [comment]
We now have elapsed time, I can add the length of the response. Both the message that a query is being processed, and the time it took are now logged at INFO level.

I strongly advise against removing the "processing query" part before a command - if I understood that suggestion right - logs of IRRd 4 are not compatible with IRRd 2 in many other places.
