### ISSUE TITLE
Database file loader command

### ISSUE THREAD

**Issue by job** [irrdnet/irrd4#172]
To refresh a database, you currently have to put the `.db` file in the correct location and wait for `import_timer` to expire. From a scripting perspective this is not entirely ideal,  as its hard for the script to know whether reload was successful or not.

perhaps a helper script can be provided that takes as arguments such as name of the database, location of the currentserial and db file. This script would be expected to reload the new contents in an atomic fashion so that if there is an error anywhere in the new file, the old file is being used (and not overwritten), the script's exit code is also significant.

The problem I'm trying to avoid is that if a program of mine produces a `.db` file with invalid contents, I'd like to prevent loading that partially into the daemon.

**Comment by mxsasha** [comment]
See https://irrd4.readthedocs.io/en/master/users/mirroring.html#manually-loading-data
