### ISSUE TITLE
include examples for logrotate and systemd

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#173]
for logrotate and systemd

ex:
to rotate the log install a file like the below:
# install as /etc/logrotate.d/irrd with permissions 0644
```
/home/irrd/server.log {
    missingok
    daily
    compress
    delaycompress
    dateext
    rotate 35
    olddir /home/irrd/logs
    postrotate
        systemctl reload irrd.service > /dev/null 2>&1 || true
    endscript
}
```

be sure to create the directory `/home/irrd/logs`

a sample system service file while using setcap looks like:
# install as /lib/systemd/system/irrd.service
```
[Unit]
Description=IRRD4 Service
Wants=basic.target
After=basic.target network.target
  
[Service]
Type=simple
WorkingDirectory=/home/irrd
User=irrd
Group=irrd
PIDFile=/home/irrd/irrd.pid
ExecStart=/home/irrd/irrd-venv/bin/twistd -n --pidfile=/home/irrd/irrd.pid irrd
Restart=on-failure
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

then run:
```
systemctl daemon-reload
systemctl enable irrd
systemctl start irrd
```

**Comment by troy2914** [comment]
Just added an ExecReload command to service file to support systemctl reload irrd.service

**Comment by mxsasha** [comment]
I can add these, that'll be helpful for other deployments. Note that I haven't tested them myself, I'm assuming you've tried them out on your server.

**Comment by job** [comment]
yes we run these on irrd01.ip.gin.ntt.net
