### ISSUE TITLE
per-thread !g caching

### ISSUE THREAD

**Issue by job** [irrdnet/irrd4#176]
Within each thread, we can have a local cache for the output from `!g` commands.

the cache is purged under the following circumstances:

- the list of sources changes compared to the last instantiation of a source modification command
- 10 minutes (configurable) pass
- the thread terminates because the tcp connection is closed

I suspect that this change will bring the NTT use case under 30 minutes. It works well in scenarios where there is a single long lived tcp session, and the `!s` sources modifier doesn't change that often, and no RIPE style queries are used.

**Comment by job** [comment]
advantages: no dependency on memcached! and each tcp session represents a single session, within this context this caching method is covering for laziness on the client side. clients *should* cache a bit, but if they dont the server can transparently do that with this method.

**Comment by mxsasha** [comment]
Decision:

- NTT is unable do adapt aclgen - it will only run a single connection and can not adopt the fast !a query
- A cache per thread will be implemented for !i, !6, !g queries. It will have no expiry, and is limited to the specific thread/connection.
- The cache is opt-in, based on a new setting with an access list of IPs for whom the cache is applied.
- The source list is part of the cache key, so queries with different source lists are cached separately.

**Comment by mxsasha** [comment]
FYI: we're placing this on hold for now, given that it looks possible to update aclgen, and pending results of tests with !a.

**Comment by job** [comment]
https://github.com/irrdnet/irrd4/issues/184 is probably a superior solution
