### ISSUE TITLE
!i6 should be supported in ipv4_only_route_set_members mode

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#189]
we originally talked about !i6 in #137 

Does not seem to be fully working in 4.0.0.rc6

in irrd.yaml there is:

    irrd:
        compatibility:
            ipv4_only_route_set_members: true

when queried for `!i6rs-gloops,1` 4.0.0rc6 returns
`D`

vs the irrd2 on rr.ntt.net

    whois -h rr.ntt.net '!i6rs-gloops,1'
    A19
    2001:218:2005::/48
    C

btw, `!i` is properly filtering out ipv6 records.

**Comment by job** [comment]
I think we decided to not use `!i6` in v4, since we're not using it?
