### ISSUE TITLE
Restrict maintainer (mntner) creation

### ISSUE THREAD

**Issue by bitcynth** [irrdnet/irrd4#212]
Currently mntner creation is unrestricted via the email interface.
There should be in my opinion a setting to restrict it to require some sort of administrative input.
Maybe @job could give some input on this?

**Comment by job** [comment]
Excellent find!

This administrative check was tasked to the `irrd/src/programs/irr_notify/*` tool:

```
irr_notify job$ grep NEW_MNT_ERROR_MSG_2 *
notify_msgs.c:      fprintf (msg_fp, "%s%s %s", ERROR_TAG, NEW_MNT_ERROR_MSG_2, db_admin);
trans_hdrs.c:const char NEW_MNT_ERROR_MSG_2[] = "New maintainers must be added by an administrator.\nForwarding new request to";
```

It would be good to replicate this behaviour in irrd4! The database administrator can use the override_pw to create any maintainer that is needed. 

@mxsasha can this be added under the support contract?

**Comment by bitcynth** [comment]
I would suggest having it as an option, so that you can configure if anyone can create a maintainer or not. but I understand that it is probably not really needed for NTT's purposes.

**Comment by job** [comment]
I do not think this should ever be optional, I don't think it was in irrd2
or irrd3 either. If it is optional, someone somewhere will deploy it
misconfigured potentially resulting open-memcached-style issues.

**Comment by bitcynth** [comment]
very true, I guess you could use the future API if you really need open maintainer registrations
