### ISSUE TITLE
deletes of route objects do not work

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#228]
In 4.0.0rc5 I had added a 
PERSON and MAINTNER
along with a ROUTE object.

Tested under 4.0.0
Trying to remove the ROUTE object
I get a"Delete FAILED"
ERROR: Object X.Y.Z.A/16ASNNN to be deleted, but still referenced by mntner MAINT-FUBAR
ERROR: Object X.Y.Z.A/16ASNNN to be deleted, but still referenced by person MRFOO
ERROR: Object X.Y.Z.A/16ASNNN to be deleted, but still referenced by key-cert GPGKEY-XXXXX

Thinking this might happen with some modifies too?

**Comment by mxsasha** [comment]
I can reproduce this locally with fresh objects, so it definitely looks like a bug. I'll investigate. It seems unrelated to these objects being created in rc5.

**Comment by mxsasha** [comment]
Modifying route objects works fine btw, deletion includes some special extra checks to maintain referential integrity, which are apparently overzealous.
