### ISSUE TITLE
Ignore IRRd v2 / v3 clutter in dump files

### ISSUE THREAD

**Issue by job** [irrdnet/irrd4#232]
**Describe the bug**
IRRd v4 sometimes has trouble loading dumps from older IRRd versions. Older IRRd instances would mark deleted objects with `*xx` as the first three chars of the object type, which meant that later on down in the file there will be a newer version of that object. This way IRRd wouldn't have to reshuffle its full flat text file database all the time.

**To Reproduce**
Today's RADB dump can't be loaded: 
 ```~irrd/irrd-venv/bin/irrd_load_database --irrd_pidfile ~irrd/irrd.pid --serial 4327229 --source RADB radb.db
Error occurred while processing object:
Unknown object class: *xxte
```
**Expected behaviour**
The `irrd_load_database` command should be able to ingest dump files that have IRR objects of object class types such as `*xx-num:`,`*xxner:`, `*xxset:`, `*xxte-set:`, `*xxte6:`, or `*xxte:`), and just ignore those without warning and not error. Just pretend that object didn't exist.

**IRRd version you are running**
E.g. 4.0.1

**Additional context**

**Comment by mxsasha** [comment]
Yes, we can do this, but see my comment #233 as well. As in, I'm not sure why you're loading RADB manually instead of through the regular mirror process.

**Comment by job** [comment]
Mirroring had broken for some reason, and the NRTM gap was too large for the source IRRd instance to fill so it wouldn't re-established, so we had to re-seed from RADB's FTP dump which contains these `*xx` prefix'ed object classes.

I agree with the tending to be strict, but in the case of `*xx` objects we know what they are and why they are there, we can safely ignore those objects.

**Comment by mxsasha** [comment]
As https://irrd4.readthedocs.io/en/latest/users/mirroring.html now says:
> Unknown object classes that start with *xx are silently ignored, as these are harmless artifacts from certain legacy IRRd versions.

**Comment by job** [comment]
this works as advertised!
