### ISSUE TITLE
Mirroring: providing exports and NRTM streams to other registries

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd4#24]
Including an access list for NRTM access.

**Comment by troy2914** [comment]
Note this needs to support both versions 2 and 3 of NRTM.   Also on the importing of NRTM streams.

And there will need to be entries in the config to specify version (2, 3, in the future 4) per registry #26

**Comment by mxsasha** [comment]
For mirroring other sources, where would we need to distinguish the NRTM version, for now? Our NRTM parser is version-agnostic, it'll work with what it can get. We now run successful mirroring with the current irrd4 codebase from:

- nrtm.ripe.net
- irr.bboi.net
- rr.arin.net
- rr.level3.net
- rr.ntt.net
- whois.radb.net
- whois.rg.net

The only NRTM versions we get from these sources, according to the headers in their NRTM stream are 1 and 3, with the only difference being whether individual ADD/DEL operations contain the serial of the change. We do not have any docs for a NRTMv2, so I don't know what that stream would look like.

**Comment by mxsasha** [comment]
Intriguing, because the NRTM header definitely specifies version 1 for several, and the format matches what RIPE NCC calls version 2.

I'm still unclear on what config bits you are suggesting. We currently do not configure which NRTM version to expect from another NRTM server, because we've not found any need to make that distinction. The parser understands both and will use what it can get.

**Comment by troy2914** [comment]
Ah, you are correct, if irrd4 importer does not care what version it is talking to, there is no configuration needed.

**Comment by mxsasha** [comment]
Note that rr.ntt.net currently support version 1 and 3 only, not version 2:
```
-g NTTCOM:1:998248-998248
%START Version: 1 nttcom 998248-998248

ADD

route:      103.122.52.0/24
descr:      Transatel proxy object
origin:     AS138199
mnt-by:     MAINT-NTTCOM-RA
changed:    ched@ntt.net 20181217
source:     NTTCOM

%END NTTCOM
-g NTTCOM:2:998248-998248



% ERROR: unsupported procotol version (2)
-g NTTCOM:3:998248-998248
%START Version: 3 nttcom 998248-998248

ADD 998248

route:      103.122.52.0/24
descr:      Transatel proxy object
origin:     AS138199
mnt-by:     MAINT-NTTCOM-RA
changed:    ched@ntt.net 20181217
source:     NTTCOM

%END NTTCOM
```

**Comment by troy2914** [comment]
Thinking maybe handling 2 as 1 is in order?
