### ISSUE TITLE
AS-SET should be able to reference AS-SET in other sources.

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#240]
Attempted in 4.0.2

Modify FAILED: [as-set] AS2914:AS-EUROPE-V6
ERROR: Object AS-1AND1 referenced in field members not found in database NTTCOM - must reference one of aut-num, as-set.
ERROR: Object AS-3W-INFRA referenced in field members not found in database NTTCOM - must reference one of aut-num, as-set.

Actually for that matter, I do not think any checks beyond valid content (ascii and of the form as-set name or asn ) of as-set/asn names, should be checked for the as-set members.  E.g. it may refer to as-set's/ASNs that do not currently exist.

**Comment by mxsasha** [comment]
I'll pick this up and validate only on valid ASN or valid as-set name. I take it the same principle should apply to rtr-set and route-set? Those also have the same strong validation now.

**Comment by job** [comment]
Correct, please also extend to those object types.
