### ISSUE TITLE
no date in "changed:" attribute should autofill a date

### ISSUE THREAD

**Issue by job** [irrdnet/irrd4#242]
When an object is submitted to the IRRd instance, the convention in version 2 and 3 was that if you'd leave out the date in the `changed:` attribute, the IRRd instance fills in the date. So submitting an object on July 1st 2019 like `changed: job@ntt.net` would autocomplete into `changed: job@ntt.net 20190701` in the database.

It is possible there is no documentation about this feature.

There also was a bug, on that note, I'd like to propose that people can't 'back date' objects. The previous IRRd versions would gladly accept `changed: job@ntt.net 17840101`. So, if people fill in no date, or any date, the IRRd should just store today's date.

Unless the `override:` is used, than the IRRd should either autocomplete to today's date, or accept the value that was submitted.

**Comment by mxsasha** [comment]
Is there any more to the format of the changed: line? Is it always `<email> YYYMMDD` or `<email>`? Are users allowed to add comments which should be retained?

(For non-override cases we wouldn't actually care which date format they used - we'll only get the e-mail address from their entry and then add our own date.)

**Comment by job** [comment]
excellent question. comments are legal in this context, so we can have:

`<email> YYYMMDD` 
or
`<email> YYYMMDD # hello comment my old friend`
or
`<email>`

as input, which could result in:

`job@ntt.net 20190702` 
or
`job@ntt.net 20190702 # hello comment my old friend`
or respectively
`job@ntt.net 20190702`

**Comment by mxsasha** [comment]
These are the proposed release notes, if you can confirm this behaviour to be correct, I can create 4.0.4:

```
In earlier versions of IRRd, format of the `changed`
attribute was entirely free. In IRRd 4.0.4, the format
is expected to be ``<email> [YYYYMMDD]` with an optional
comment, as allowed with other RPSL attributes. The date
is optional. Regardless of the date, if any, set in the
attribute, it will be overwritten by today's date,
unless the override password was used. Pre-existing
`changed` attributes are not affected.
```
