### ISSUE TITLE
Consider adding pytest 5.1.0 compatibility.

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd4#249]
In https://github.com/irrdnet/irrd4/pull/248 pyup tried to upgrade pytest to 5.1.0, which breaks the way we check exceptions somehow. For now, it's pinned to version <5. Compatibility with the most recent version would be nice, but isn't too important. It does not affect production deployments in any way.

See https://circleci.com/gh/irrdnet/irrd4/878 for what the failures look like.

**Comment by kkirsche** [comment]
Would there be any interest in a pull request to fix this or other issues like this?

**Comment by job** [comment]
I’d certainly be interested to review such a proposal.

**Comment by kkirsche** [comment]
@job I've submitted a pull request which updates pytest to the latest version, 5.1.2, and fixes the exception syntax. Please let me know if there are any questions or concerns.
