### ISSUE TITLE
exported db.gz has too strict permissions.

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#258]
The CURRENTSERIAL file is 0644
But the .db.gz is 0600

/etc/irrd.yaml contained
        INTERNAL:
            authoritative: true
            nrtm_access_list: generic_nrtm_access
            keep_journal: true
            export_destination: /home/irrd/dbs
            export_timer: 3600

I would expect both the CURRENTSERIAL and db.gz to be have
the same permissions, ie 0644.

version 4.0.6

This irrd was running from a service definition that does not explicitly list the umask,
so 0022 is the default.

**Comment by kkirsche** [comment]
If I understand correctly, this is related to this function:
https://github.com/irrdnet/irrd4/blob/master/irrd/mirroring/mirror_runners_export.py#L45

Is this correct?

**Comment by troy2914** [comment]
Yes, I believe that is correct.
