### ISSUE TITLE
user reported exported db.gz concerns

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#268]
apparently in irrd2/3 the export file ends with  "# EOF"

also apparently the objects are not being exported in a consistent order (between exports at time 1 and time 2).

**Comment by mxsasha** [comment]
We can add an "# EOF" marker to the end of export files. For ordering, we currently order on associated IP first, ASN second. That leaves objects that have neither, and those might not be in a deterministic order right now. I will look into it.

**Comment by job** [comment]
On Thu, Nov 07, 2019 at 05:02:20AM -0800, Sasha Romijn wrote:
> We can add an "# EOF" marker to the end of export files.

that is nice

> For ordering, we currently order on associated IP first, ASN second.
> That leaves objects that have neither, and those might not be in a
> deterministic order right now. I will look into it.

Any type of determinstic sorting probably is fine, unix sort on the
primary key lines, or just .sorted()

**Comment by mxsasha** [comment]
Released in 4.0.8.
