### ISSUE TITLE
Queries: open questions about queries

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd4#37]
A few questions for @job, which I haven't been able to clear up using the IRRd source code:

* What exactly is searched for in RIPE-style free text queries? E.g. if the only query input is "NTT" or "192.0.2.0/24"?
* What are the rules for retrieving related objects? Retrieve all associated tech-c/admin-c/zone-c objects and include them in the result? And for which queries should related objects be included? (provided -r hasn't been included)
* What is the -V query flag for? I can't seem to get any results out of it, nor find any documentation on it.

**Comment by mxsasha** [comment]
New question: in case of a `!g` or `!6` query, should duplicate results (i.e. exactly the same prefix) be deduplicated, or should all entries be returned?

**Comment by job** [comment]
@mxsasha `!g` and `!6` should deduplicate exact same prefixes. There is no point in returning those to the client

**Comment by job** [comment]
`-V` is a command probably designed to be more compatible with the RIPE DB:

```job@vurt ~$ whois -h rr.ntt.net -- '-V clientidentifier,127.0.0.1 165.254.255.0/24'
route:      165.254.255.0/24
descr:      Job Snijders2
origin:     AS15562
notify:     job@instituut.net
mnt-by:     MAINT-JOB
changed:    job@ntt.net 20170726
source:     NTTCOM
```
We should look if this flag is *ever* used against IRRd, if not no need to implement it.

**Comment by job** [comment]
> What exactly is searched for in RIPE-style free text queries? E.g. if the only query input is "NTT" or "192.0.2.0/24"?

I think a sort of wildcard search through all primary keys:

```
job@vurt ~$ whois -h rr.ntt.net NTT | grep person:
person:             NTT Verio SME Business Unit
person:     NTT Communiations
person:     NTT Communiations Global IP Network Engineering
job@vurt ~$ whois -h rr.ntt.net 165.254.255.0/24 | grep route:
route:      165.254.255.0/24
job@vurt ~$ whois -h rr.ntt.net AS15562 | grep aut-num:
aut-num:        AS15562
```

**Comment by job** [comment]
> What are the rules for retrieving related objects? Retrieve all associated tech-c/admin-c/zone-c objects and include them in the result? And for which queries should related objects be included? (provided -r hasn't been included)

If the search key is an IP address (or network), return all route objects which cover (contain) the requested search key.

If the search key is an AS number, return the `aut-num` object or (if it exists) the covering `as-block` object.

For other objects I don't know from the top of my head. If it isnt clear from source code, perhaps it can be reverse engineered from `rr.ntt.net` and `whois.radb.net` ?

**Comment by mxsasha** [comment]
Yes, but with related objects I meant: in which cases are the associated role/person objects returned, that are listed in tech-c/admin-c/zone-c? (The behaviour `-r` prevents.)

**Comment by job** [comment]
I'm actually not sure person/role objects are ever returned as 'related'
when querying for IP or ASN to IRRd

**Comment by mxsasha** [comment]
> I'm actually not sure person/role objects are ever returned as 'related'
when querying for IP or ASN to IRRd

I thought I saw it somewhere, but can't replicate it now. Looking at the IRRD3 code again, I also don't see an actual implementation of recursion for this. So the `-r` flag should be accepted but has no effect. I'll leave `-V` out of the implementation for now.

**Comment by job** [comment]
@mxsasha I found someone that uses `-V`, so we probably should implement some shim support:

`-V $arg1 $@rest_of_args`

`$arg1` is a string that identifies the client, the rest of what follows after is a regular whois command, example:

`-V IRRToolSet4.8.4 -r -K -i origin AS3932`
