### ISSUE TITLE
Parsing issue: RGNET contains objects without a source

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd4#68]
```
route:      216.21.16.0/24
descr:      PSGnet/ESnet
origin:     AS3445
notify:     rw@rg.net
mnt-by:     MAINT-RGNET
changed:    randy@psg.com 20170313

route:      216.151.36.0/24
descr:      PSGnet/ESnet
origin:     AS3445
notify:     rw@rg.net
mnt-by:     MAINT-RGNET
changed:    randy@psg.com 20170313

route:      216.151.41.0/24
descr:      PSGnet/ESnet
origin:     AS3445
notify:     rw@rg.net
mnt-by:     MAINT-RGNET
changed:    randy@psg.com 20170313
```

These objects can't be imported, because the source attribute is how we distinguish objects from different databases, so it's essential. It affects these three objects at least, perhaps more.

The parser also currently crashes when encountering these objects, but this should just be an object validation error.

**Comment by mahtin** [comment]
@mxsasha - are you sure? I just dumped "rgnet.db.gz" from ftp://ftp.radb.net/radb/dbase and it looks fine. All records marked with "**source: RGNET**"

**Comment by job** [comment]
ftp://rg.net/rgnet/RGNET.db.gz is the canonical copy, and shows some objects that lack the source. Look for `route: 216.21.16.0/24`

**Comment by mxsasha** [comment]
This is also how it's served from their IRR server:
```
$ whois -h whois.rg.net 216.21.16.0/24
route:      216.21.16.0/24
descr:      PSGnet/ESnet
origin:     AS3445
notify:     rw@rg.net
mnt-by:     MAINT-RGNET
changed:    randy@psg.com 20170313
```

**Comment by job** [comment]
RGNET fixed these

**Comment by mxsasha** [comment]
This was fixed and verified yesterday.
