### ISSUE TITLE
Remove auth hashes from query output?

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd4#74]
@job should we do this in all cases? And if someone submits and update, they either need to re-provide hashes for all password auth methods, or if they keep the placeholder value, we simply keep what we have in the DB?

**Comment by job** [comment]
Yes - always hide the hashes.

If the placeholders are submitted "back" to IRRd - we can keep one placeholder (the one against which was successfully authenticated), if someone wants to keep all hash auth methods, they'd need to provide all hashes

**Comment by mxsasha** [comment]
@job since hashes are never shown, can we just re-generate the hash instead?

So, current object internally in the DB:
```
mntner:         FOO-MNT
auth:           PGPKey-80F238C6
auth:           CRYPT-PW LEuuhsBJNFV0Q  # crypt-password
auth:           MD5-PW $1$fgW84Y9r$kKEn9MUq8PChNKpQhO6BM.  # md5-password
auth:           MD5-PW some-other-hash
```

Returned from a query
```
mntner:         FOO-MNT
auth:           PGPKey-80F238C6
auth:           CRYPT-PW DummyValue  # filtered for security
auth:           MD5-PW DummyValue  # filtered for security
auth:           MD5-PW DummyValue  # filtered for security
```

Submitted to database:
```
mntner:         FOO-MNT
auth:           PGPKey-80F238C6
auth:           CRYPT-PW DummyValue  # filtered for security
auth:           MD5-PW DummyValue  # filtered for security
auth:           MD5-PW DummyValue  # filtered for security
password: md5-password
```

Now stored in the database:
```
mntner:         FOO-MNT
auth:           PGPKey-80F238C6
auth:           MD5-PW other-hash-that-matches-string-md5-password
```

Generating a new hash from the password (knowing that the password is valid), rather than reusing the old hash, makes implementation a bit simpler. As nobody can ever see the hash values, there is no way for them to know, right?

To make it even simpler, and progressively secure, we could automatically upgrade hashes to MD5-PW when the submitted password matches a CRYPT-PW.

**Comment by mxsasha** [comment]
The above, including encoding the new password always as MD5-PW, is now part of #83.

**Comment by job** [comment]
I like the idea of regenerating the hashes

**Comment by mxsasha** [comment]
Additional task: emit INFO messages when hashes are auto-replaced.
