### ISSUE TITLE
Missing source info for complete copy of current NTT IRRD

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd4#93]
We can pull most sources directly from their origin or through RADB, but we are missing ARIN-WHOIS, RPKI, REGISTROBR and INTERNAL. For #19, it's important we have the same database as current NTT, so we need dumps of these sources.

**Comment by mxsasha** [comment]
I'm also unclear on where to find reliable dumps of ALTDB, BBOI, BELL, JPIRR, TC. Downloads from RADB FTP, NRTM from rr.ntt.net?

**Comment by job** [comment]
Yes

**Comment by troy2914** [comment]
> I'm also unclear on where to find reliable dumps of ALTDB, BELL, JPIRR, TC. Downloads from RADB FTP, NRTM from rr.ntt.net?

http://www.irr.net/docs/list.html has links to the dumps for 
those sources.  Alas the BELL ftp site seems fubar.  And TC ftp site does not seem to be running ftp anymore.

**Comment by job** [comment]
dumps are available now here:

```root@irrd01.dascare.nl:~# ls db_dumps/
AFRINIC.CURRENTSERIAL     GT.CURRENTSERIAL          RGNET.CURRENTSERIAL
afrinic.db                gt.db                     rgnet.db
ALTDB.CURRENTSERIAL       INTERNAL.CURRENTSERIAL    RIPE.CURRENTSERIAL
altdb.db                  internal.db               ripe.db
APNIC.CURRENTSERIAL       JPIRR.CURRENTSERIAL       RIPE-NONAUTH.CURRENTSERIAL
apnic.db                  jpirr.db                  ripe-nonauth.db
ARIN.CURRENTSERIAL        LEVEL3.CURRENTSERIAL      RPKI.CURRENTSERIAL
arin.db                   level3.db                 rpki.db
ARIN-WHOIS.CURRENTSERIAL  NTTCOM.CURRENTSERIAL      SAVVIS.CURRENTSERIAL
arin-whois.db             nttcom.db                 savvis.db
BBOI.CURRENTSERIAL        RADB.CURRENTSERIAL        TC.CURRENTSERIAL
bboi.db                   radb.db                   tc.db
BELL.CURRENTSERIAL        REGISTROBR.CURRENTSERIAL
bell.db                   registrobr.db
root@irrd01:~#```

**Comment by mxsasha** [comment]
Thanks. We will use these copies to load the data for #117, which in turn is needed by #19.
